# ════════════════════════════════════════
#  COLORS  (theme-aware)
#  Auto-generated by: python pywindui.py --theme
# ════════════════════════════════════════

class Colors(str):

    _themes: dict[str, dict[str, str]] = {

        # ── Dark ────────────────────────────
        "dark": {
            "bg":                    "#0f172a",
            "bg_secondary":          "#111113",
            "fg":                    "#d1d5db",
            "card":                  "#1e293b",
            "card_fg":               "#d1d5db",
            "popover":               "#1e293b",
            "popover_fg":            "#d1d5db",
            "primary":               "#34d399",
            "primary_fg":            "#0f172a",
            "secondary":             "#2d3748",
            "secondary_fg":          "#a1a1aa",
            "muted":                 "#19212e",
            "muted_fg":              "#6b7280",
            "accent":                "#374151",
            "accent_fg":             "#a1a1aa",
            "destructive":           "#ef4444",
            "destructive_fg":        "#0f172a",
            "success":               "#22c55e",
            "success_fg":            "#ffffff",
            "warning":               "#f59e0b",
            "warning_fg":            "#ffffff",
            "border":                "#4b5563",
            "input":                 "#4b5563",
            "ring":                  "#34d399",
            "chart_1":               "#34d399",
            "chart_2":               "#2dd4bf",
            "chart_3":               "#22c55e",
            "chart_4":               "#10b981",
            "chart_5":               "#059669",
            "sidebar":               "#1e293b",
            "sidebar_fg":            "#d1d5db",
            "sidebar_primary":       "#34d399",
            "sidebar_primary_fg":    "#0f172a",
            "sidebar_accent":        "#374151",
            "sidebar_accent_fg":     "#a1a1aa",
            "sidebar_border":        "#4b5563",
            "sidebar_ring":          "#34d399",
            "black":                 "#000000",
            "white":                 "#ffffff",
        },

        # ── Light ───────────────────────────
        "light": {
            "bg":                    "#f0f8ff",
            "bg_secondary":          "#f5f5f5",
            "fg":                    "#374151",
            "card":                  "#ffffff",
            "card_fg":               "#374151",
            "popover":               "#ffffff",
            "popover_fg":            "#374151",
            "primary":               "#22c55e",
            "primary_fg":            "#ffffff",
            "secondary":             "#e0f2fe",
            "secondary_fg":          "#4b5563",
            "muted":                 "#f3f4f6",
            "muted_fg":              "#6b7280",
            "accent":                "#d1fae5",
            "accent_fg":             "#374151",
            "destructive":           "#ef4444",
            "destructive_fg":        "#ffffff",
            "success":               "#22c55e",
            "success_fg":            "#ffffff",
            "warning":               "#f59e0b",
            "warning_fg":            "#ffffff",
            "border":                "#e5e7eb",
            "input":                 "#e5e7eb",
            "ring":                  "#22c55e",
            "chart_1":               "#22c55e",
            "chart_2":               "#10b981",
            "chart_3":               "#059669",
            "chart_4":               "#047857",
            "chart_5":               "#065f46",
            "sidebar":               "#e0f2fe",
            "sidebar_fg":            "#374151",
            "sidebar_primary":       "#22c55e",
            "sidebar_primary_fg":    "#ffffff",
            "sidebar_accent":        "#d1fae5",
            "sidebar_accent_fg":     "#374151",
            "sidebar_border":        "#e5e7eb",
            "sidebar_ring":          "#22c55e",
            "black":                 "#000000",
            "white":                 "#ffffff",
        },
    }

    _current_theme: str = "dark"

    # ── Static defaults (dark) so Pylance can see them ──
    bg:                    str = "#0f172a"
    bg_secondary:          str = "#111113"
    fg:                    str = "#d1d5db"
    card:                  str = "#1e293b"
    card_fg:               str = "#d1d5db"
    popover:               str = "#1e293b"
    popover_fg:            str = "#d1d5db"
    primary:               str = "#34d399"
    primary_fg:            str = "#0f172a"
    secondary:             str = "#2d3748"
    secondary_fg:          str = "#a1a1aa"
    muted:                 str = "#19212e"
    muted_fg:              str = "#6b7280"
    accent:                str = "#374151"
    accent_fg:             str = "#a1a1aa"
    destructive:           str = "#ef4444"
    destructive_fg:        str = "#0f172a"
    success:               str = "#22c55e"
    success_fg:            str = "#ffffff"
    warning:               str = "#f59e0b"
    warning_fg:            str = "#ffffff"
    border:                str = "#4b5563"
    input:                 str = "#4b5563"
    ring:                  str = "#34d399"
    chart_1:               str = "#34d399"
    chart_2:               str = "#2dd4bf"
    chart_3:               str = "#22c55e"
    chart_4:               str = "#10b981"
    chart_5:               str = "#059669"
    sidebar:               str = "#1e293b"
    sidebar_fg:            str = "#d1d5db"
    sidebar_primary:       str = "#34d399"
    sidebar_primary_fg:    str = "#0f172a"
    sidebar_accent:        str = "#374151"
    sidebar_accent_fg:     str = "#a1a1aa"
    sidebar_border:        str = "#4b5563"
    sidebar_ring:          str = "#34d399"
    black:                 str = "#000000"
    white:                 str = "#ffffff"

    # ── instance constructor ────────────
    def __new__(cls, theme: str = "dark"):
        return super().__new__(cls, theme)

    def __init__(self, theme: str = "dark"):
        if theme not in self._themes:
            raise ValueError(
                f"Unknown theme '{theme}'. "
                f"Available: {list(self._themes.keys())}"
            )
        for key, value in self._themes[theme].items():
            setattr(self, key, value)

    # ── class-level theme switch ────────
    @classmethod
    def set_theme(cls, theme: str) -> None:
        """Switch the global (class-level) color theme."""
        if theme not in cls._themes:
            raise ValueError(
                f"Unknown theme '{theme}'. "
                f"Available: {list(cls._themes.keys())}"
            )
        for key, value in cls._themes[theme].items():
            setattr(cls, key, value)
        cls._current_theme = theme

    @classmethod
    def get_theme(cls) -> str:
        """Return the name of the active global theme."""
        return cls._current_theme

    @classmethod
    def register_theme(cls, name: str, tokens: dict[str, str]) -> None:
        """Add a custom theme at runtime."""
        cls._themes[name] = tokens

def Alpha(color, Alpha=1.0):
    """opacity from 0.0 to 1.0"""
    alpha = format(int(Alpha * 255), "02x")
    return "#" + alpha + color.lstrip("#")
